### ISSUE TITLE
Expose loading_application_id as an input to the \write end point

### ISSUE THREAD

**Issue by tjrocha** [usbr/HdbApi#10]

**Comment by tjrocha** [comment]
Also expose agen_id

**Comment by beautah** [comment]
Not sure if Carol asked for this or whomever, but this is a great addition.
Much appreciated

**Comment by tjrocha** [comment]
Implemented in commit a12d91082d690ce592f7c45b498f815b9811dca1. Pushed to production. All nunit and user tests pass. Closing ticket.
